# Generated by Django 5.0.1 on 2025-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='mail',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
