# Generated by Django 5.0.1 on 2025-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicerequest_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
