# Generated by Django 5.0.1 on 2025-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicerequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='mail',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
