# Generated by Django 5.0.1 on 2025-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='mail',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
