# Generated by Django 5.0.1 on 2025-01-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicerequest_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='mail',
        ),
    ]
