# Generated by Django 5.0.1 on 2025-01-15 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
